routes/admin.php
<?php

use App\Http\Controllers\Admin\MainSliderController;
use App\Http\Controllers\Admin\SettingController;
use App\Http\Controllers\Admin\UserController;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\Admin\ProductController;
use \App\Http\Controllers\Admin\ArticleController;
use App\Http\Controllers\Admin\CategoryController;
use App\Http\Controllers\Admin\RubricController;

Route::get('/', [UserController::class, 'index'])->name('index');
Route::get('users', [UserController::class, 'users'])->name('users');
Route::get('user/create', [UserController::class, 'create'])->name('user-create');
Route::get('user/{id}/edit', [UserController::class, 'edit'])->name('user-edit');
Route::get('user/{id}/delete', [UserController::class, 'delete'])->name('user-delete');
Route::post('user/save', [UserController::class, 'save'])->name('user-save');
Route::get('user/products/favorites/{user}', [UserController::class, 'favoriteUser'])->name('user-favorite');

Route::get('settings', [SettingController::class, 'index'])->name('settings');
Route::post('settings/save', [SettingController::class, 'save'])->name('settings-save');

Route::get('sliders/main', [MainSliderController::class, 'index'])->name('main-slider.index');
Route::get('sliders/main/edit/{mainSlider}', [MainSliderController::class, 'edit'])->name('main-slider.edit');
Route::get('sliders/main/delete/{mainSlider}', [MainSliderController::class, 'delete'])->name('main-slider.delete');
Route::post('sliders/main/save', [MainSliderController::class, 'save'])->name('main-slider.save');

Route::get('product', [ProductController::class, 'index'])->name('product.index');
Route::get('product/create', [ProductController::class, 'create'])->name('product.create');
Route::get('product/edit/{product}', [ProductController::class, 'edit'])->name('product.edit');
Route::get('product/delete/{product}', [ProductController::class, 'delete'])->name('product.delete');
Route::post('product/save', [ProductController::class, 'save'])->name('product.save');
Route::get('product/images/{product}', [ProductController::class, 'images'])->name('product.images');
Route::post('product/image/upload', [ProductController::class, 'imageUpload'])->name('product.image-upload');
Route::get('product/image/delete/{productImage}', [ProductController::class, 'imageDelete'])->name('product.image-delete');

Route::get('articles', [ArticleController::class, 'index'])->name('article.index');
Route::get('article/create', [ArticleController::class, 'create'])->name('article.create');
Route::get('article/edit/{id}', [ArticleController::class, 'edit'])->name('article.edit');
Route::post('article/save', [ArticleController::class, 'save'])->name('article.save');
Route::get('article/delete/{article}', [ArticleController::class, 'delete'])->name('article.delete');

Route::get('rubrics', [RubricController::class, 'index'])->name('rubric.index');
Route::get('rubric/create', [RubricController::class, 'create'])->name('rubric.create');
Route::get('rubric/edit/{id}', [RubricController::class, 'edit'])->name('rubric.edit');
Route::post('rubric/save', [RubricController::class, 'save'])->name('rubric.save');
Route::get('rubric/delete/{id}', [RubricController::class, 'delete'])->name('rubric.delete');

Route::get('category', [CategoryController::class, 'index'])->name('category.index');
Route::get('category/create', [CategoryController::class, 'create'])->name('category.create');
Route::get('category/edit/{category}', [CategoryController::class, 'edit'])->name('category.edit');
Route::get('category/delete/{category}', [CategoryController::class, 'delete'])->name('category.delete');
Route::post('category/save', [CategoryController::class, 'save'])->name('category.save');

routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use Illuminate\Support\Facades\Auth;
use App\Http\Controllers\PublicController;
use App\Http\Controllers\ProfileController;
use App\Http\Controllers\BlogController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes(['logout' => false]);
Route::get('/logout',[App\Http\Controllers\Auth\LoginController::class,'logout'])->name('logout');
Route::get('/set-locale/{locale}',[PublicController::class,'setLocale'])->name('set-locale');

Route::group(['middleware' => 'HtmlMinifier'], function() {
    Route::get('/', [App\Http\Controllers\PublicController::class, 'index'])
         ->name('index');

    Route::get('/category/{category}/product/{slug}', [PublicController::class, 'product'])
         ->name('public-product');
    Route::get('/moi-tovari', [PublicController::class, 'favorite'])
         ->name('favorite');
    Route::view('/dostavka-i-oplata', 'public.deliver')
         ->name('public.delivery');
    Route::view('/kontakti', 'public.contacts')
         ->name('public.contacts');

    Route::get('/data/get', [PublicController::class, 'getData'])
         ->name('public.get-data');
    Route::get('/favorite/add/{product}', [PublicController::class, 'addToFavorite'])
         ->name('public.add-to-favorite');

    Route::get('cart/add/{product}', [PublicController::class, 'addToCart'])
         ->name('public.add-to-cart');
    Route::get('cart/product/{product}/set-count/{count}', [PublicController::class, 'setCount'])
         ->name('public.cart-set-count');
    Route::get('cart/remove/{product}', [PublicController::class, 'removeFromCart'])
         ->name('public.remove-from-cart');
    Route::get('cart/clear', [PublicController::class, 'cartClear'])
         ->name('public.cart-clear');

    Route::get('rubrics', [BlogController::class, 'index'])
         ->name('public.rubric-index');
    Route::get('rubric/{slug}', [BlogController::class, 'rubric'])
         ->name('public.rubric');
    Route::get('rubric/{rubricSlug}/article/{articleSlug}', [BlogController::class, 'article'])
         ->name('public-article');

    Route::get('/api/login', [\App\Http\Controllers\Auth\LoginController::class, 'apiLogin']);

    Route::prefix('profile')
         ->group(function () {
             Route::get('/', [ProfileController::class, 'index'])
                  ->name('profile');
             Route::post('/save', [ProfileController::class, 'save'])
                  ->name('profile-save');
         });
});

//examples
Route::view('/example/modal','example.modal');

app/Models/MainSlider.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class MainSlider extends Model
{
    const TYPE_DESKTOP = 1;
    const TYPE_MOBILE = 2;

    use HasFactory;

    protected $fillable = ['id', 'type_id'];

    public $timestamps = false;

    public function getFullPathAttribute(){
        return '/storage/' . $this->path;
    }

    /**
     * Image saver for Service
     * @param $image
     */

    public function setImage($image){
        $this->path = $image;
        $this->save();
    }
}

resources/views/admin/sliders/main.blade.php
@extends('layouts.admin')
<?php
/**
 * @mixin \App\Models\MainSlider
 */
?>
@section('content')
    <h2>
        @if($mainSlider->exists())
            @lang("Слайдер: #$mainSlider->id")
        @else
            @lang("Cлайдер: Главный")
        @endif
    </h2>
    <form action="{{ route('admin-main-slider.save') }}" method="post" enctype="multipart/form-data">
        @csrf
        <input type="hidden" name="id" value="{{ $mainSlider->id }}">
        <div class="row">
            <div class="col-lg">
                <label for="type_id">@lang("Отображение")</label>
                <select name="type_id" id="type_id" class="form-control" required>
                    <option
                        value="{{ $mainSlider::TYPE_DESKTOP }}" {{ attr_selected($mainSlider->type_id == $mainSlider::TYPE_DESKTOP) }}>@lang("admin.main_slider_type_1")</option>
                    <option
                        value="{{ $mainSlider::TYPE_MOBILE }}" {{ attr_selected($mainSlider->type_id == $mainSlider::TYPE_MOBILE) }}>@lang("admin.main_slider_type_2")</option>
                </select>
            </div>
            <div class="col-lg">
                <label for="type_id">@lang("Картинка")</label>
                <input type="file" name="file" id="file" class="form-control" accept="image/jpeg image/png"
                    {{ $mainSlider->exists() ? '' : 'required'}}>
                @if($mainSlider->path)
                    <img src="{{ $mainSlider->full_path }}" alt="" class="img-fluid mt-2">
                @endif
            </div>
        </div>
        <div class="text-end mt-3">
            <button type="submit" class="btn btn-primary btn-sm">
                <i class="fa fa-save"></i>
                @lang("Сохранить")
            </button>
        </div>
    </form>
    @if(count($images))
        <div class="table-responsive mt-3">
            <table class="table table-striped table-sm table-hover">
                <thead>
                <tr>
                    <th>ID</th>
                    <th>Оторбражение</th>
                    <th>Картинка</th>
                    <th>*</th>
                </tr>
                </thead>
                <tbody>
                @foreach($images as $image)
                    <tr>
                        <td>{{ $image->id }}</td>
                        <td>
                            @lang("admin.main_slider_type_$image->type_id")
                        </td>
                        <td>
                            <a href="{{ $image->full_path }}" data-fancybox>
                                <img src="{{ $image->full_path }}" alt="" class="img-fluid" width="50">
                            </a>
                        </td>
                        <td>

                            <a href="{{ route('admin-main-slider.edit', ['mainSlider' => $image]) }}"
                               class="link-dark">
                                <i class="fa fa-edit"></i>
                            </a>
                            <a href="{{ route('admin-main-slider.delete', ['mainSlider' => $image]) }}"
                               class="link-danger" data-confirm="Уверенны?">
                                <i class="fa fa-trash"></i>
                            </a>
                        </td>
                    </tr>
                @endforeach
                </tbody>
            </table>
        </div>
    @elseif(!$mainSlider->exists())
        <div class="row">
            <div class="col-12">
                <div class="alert alert-warning mt-3" role="alert">
                    Картинок нет...
                </div>
            </div>
        </div>
    @endif
@endsection